django3545/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('surveyville/', include('django.contrib.auth.urls')),
    path('surveyville/', include('surveyville.urls')),
]

surveyville/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('newsurvey/', views.newsurvey, name='newsurvey'),
    path('survey/<int:para>', views.joinsurvey, name='joinsurvey'),
    path('surveyresult/<int:para>', views.surveyresult, name='surveyresult'),
    path('createuser/', views.createuser, name='createuser'),
    path('signin/', views.signin, name='signin'),
    path('logout/', views.logout_view, name='logout'),
    path('createsurvey/', views.createsurvey, name='createsurvey'),
    path('submitsurvey/', views.submitsurvey, name='submitsurvey'),
]

surveyville/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, UserManager


# Create your models here.
class Account(AbstractBaseUser):
    USERNAME_FIELD = 'username'
    username = models.CharField(max_length=255, unique=True)
    email = models.EmailField(max_length = 254)
    password = models.CharField(("password"), max_length=128)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    objects = UserManager()

class Survey(models.Model):
    s_title = models.CharField(max_length=255)
    s_text = models.CharField(max_length=255)
    create_date = models.DateField()
    expire_date = models.DateField()
    user_FK = models.ForeignKey(Account, on_delete=models.CASCADE)

class Question(models.Model):
    q_text = models.CharField(max_length=255)
    survey_FK = models.ForeignKey(Survey, on_delete=models.CASCADE)

class Answer(models.Model):
    a_text = models.CharField(max_length=255)
    question_FK = models.ForeignKey(Question, on_delete=models.CASCADE)

class Vote(models.Model):
    answer_FK = models.ForeignKey(Answer, on_delete=models.CASCADE)
    user_FK = models.ForeignKey(Account, on_delete=models.CASCADE)

surveyville/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from .models import *
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate, login, logout
from datetime import datetime, date, timedelta
from django.contrib.auth.models import User
from django.contrib.sessions.models import Session
from django.db.models import Count, F

def index(request):
    surveyposts = Survey.objects.annotate(participations=Count('question__answer__vote__user_FK_id', distinct=True), questioncount=Count('question__id', distinct=True)).order_by('-id')
    context = {}
    context['surveys'] = surveyposts

    context['today'] = date.today()
    if request.user.is_authenticated:
        context['user'] = request.user

    return render(
        request,
        'index.html',
        context
    )
    
def surveyresult(request, para):
    surveypost = Survey.objects.get(id=para)
    context = {}
    context['survey'] = surveypost
    context['today'] = date.today()
    if request.user.is_authenticated:
        context['user'] = request.user

    questions = Question.objects.filter(survey_FK_id=para).prefetch_related('answer_set__vote_set')
    # .annotate(votes=Count('answer__vote__answer_FK_id'))
    print(questions.query)
    context['questions'] = questions

    return render(
        request,
        'surveyresult.html',
        context
    )

@csrf_exempt
def joinsurvey(request, para):
    if request.user.is_authenticated:
        context = {}
        context['today'] = date.today()
        context['user'] = request.user
        context['survey'] = Survey.objects.get(id=para)

        # questions = Question.objects.filter(survey_FK_id=para).prefetch_related('answer').all()
        questions = Question.objects.filter(survey_FK_id=para).prefetch_related('answer_set').all()
        context['questions'] = questions
        
        return render(
            request,
            'survey.html',
            context
        )
    else:
        return redirect('index')
    
def newsurvey(request):
    if request.user.is_authenticated:
        context = {
            'user': request.user
        }
        return render(
            request,
            'newsurvey.html',
            context
        )
    else:
        return redirect('index')

@csrf_exempt
def createuser(request):
    x = request.POST['username']
    y = request.POST['password']
    z = request.POST['email']
    user = Account.objects.create_user(username=x, password=y, email=z)
    # user = Account(username=x, password=y)
    # üstteki kod hashleme yapmaz, authenticate hashli şifre aradığı için kullanıcıyı bulamaz.
    user.save()

    # Kayıt olma tamamlandıktan sonra giriş yapma işlemi
    user = authenticate(username=x, password=y)
    if user is not None:
        login(request, user)
    return redirect('index')

@csrf_exempt
def signin(request):
    x = request.POST['username']
    y = request.POST['password']
    
    user = authenticate(username=x, password=y)
    if user is not None:
        login(request, user)
        print("Success")
    else:
        print("Login failed")
    return redirect('index')


def logout_view(request):
    logout(request)
    return redirect('index')

@csrf_exempt
def createsurvey(request):
    if request.user.is_authenticated:
        questionids = request.POST.getlist('questionid')
        questions = dict({})
        for questionid in questionids:
            questiontext = request.POST[questionid + '-question']
            qanswers = tuple(request.POST.getlist(questionid + '-answer'))
            questions[questionid] = {"q": questiontext, "a": qanswers}

        # Finding the expire date.
        today = datetime.today().strftime('%Y-%m-%d')
        begindate = datetime.strptime(today, "%Y-%m-%d")
        expiredate = datetime.strftime(begindate + timedelta(days=int(request.POST['expiredate'])), '%Y-%m-%d')
        
        # Here, I am updating the database
        survey = Survey.objects.create(
            s_title=request.POST['surveytitle'],
            s_text=request.POST['description'],
            create_date=today,
            expire_date=expiredate,
            user_FK=request.user
        )
        # q = question , a = answers
        for q in questions.items():
            #print(q[1]["q"])
            question = Question.objects.create(
                q_text = q[1]["q"],
                survey_FK = survey
            )
            
            getanswers = q[1]["a"]
            for a in getanswers:
                #print(a)
                answer = Answer.objects.create(
                    a_text = a,
                    question_FK = question
                )
    return redirect('index')


@csrf_exempt
def submitsurvey(request):
    if request.user.is_authenticated:
        qids = request.POST.getlist('question')
        for qid in qids:
            Vote.objects.create(
                answer_FK_id = request.POST[qid + '-answer'],
                user_FK_id = request.user.id
            )
    return redirect('index')

surveyville/templates/index.html
{% extends "template_1.html" %}

{% block content %}
<div class="long_text_layout long_text_col_2 gallery">
    <ul class="survey_ul">
        {% for survey in surveys %}
        <li>
            <div class="desc">
                <h5>{{survey.s_title}}</h5>
                <span class="expire_date">
                    {% if today < survey.expire_date %}
                    Kalan süre: {{ today|timesince:survey.expire_date }}
                    {% else %}
                    Süre doldu
                    {% endif %}
                </span>
                <p>{{survey.s_text}}</p>
                <p><b>{{survey.participations}} Katılımcı - {{survey.questioncount}} Soru</b></p>
                {% if today < survey.expire_date %}
                <input type="button" value="Ankete Katıl" class="anket-btn" onclick="location.href='{% url 'joinsurvey' survey.id %}'">
                {% else %}
                <input type="button" value="Sonuçlar" class="anket-btn" onclick="location.href='{% url 'surveyresult' survey.id %}'">
                {% endif %}
            </div>
        </li>
        {% endfor %}
        <!--
        <li>
            <div class="desc">
                <h5>Sosyal medya uygulaması anketi</h5>
                <span class="expire_date">2 gün kaldı</span>
                <p>Bu ankete katılarak sosyal medya uygulamalarını oylayın.</p>
                <p><b>221 Katılımcı</b></p>
                <input type="button" value="Ankete Katıl" class="anket-btn">
            </div>
        </li>
        -->
    </ul>
</div>
<div class="pager_nav">
    <a href="#">1</a><span>2</span><a href="#">3</a><a href="#">4</a><a href="#">5</a>
    <a href="#" class="bx-prev">prev</a><a href="#" class="bx-next">next</a>
</div>
<!-- /pager_nav -->
{% endblock content %}

surveyville/templates/newsurvey.html
{% extends "template_1.html" %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static '/css/newsurvey.css' %}">
<script src="{% static '/js/newsurvey.js' %}"></script>
{% endblock head %}

{% block content %}
<form action="{% url 'createsurvey' %}" method="post" name="surveyform" class="surveyform">
    <div class="ns-top_container">
        <span>Başlık:</span>
        <input name="surveytitle" type="text" placeholder="Başlık">
        <span>Açıklama:</span>
        <textarea name="description" rows="3" placeholder="Açıklama"></textarea>
        <div class="expiredate">
            <span>Süre seçiniz:</span>
            <select name="expiredate">
                <option value="1" selected>1 Gün</option>
                <option value="2">2 Gün</option>
                <option value="3">3 Gün</option>
                <option value="4">4 Gün</option>
                <option value="5">5 Gün</option>
                <option value="6">6 Gün</option>
                <option value="7">1 Hafta</option>
                <option value="14">2 Hafta</option>
                <option value="30">1 Ay</option>
                <option value="60">2 Ay</option>
                <option value="90">3 Ay</option>
            </select>
            <input type="submit" class="createsurvey_btn" value="Bitir">
        </div>
    </div>
    <div class="ns-questions">
        <div class="ns-left_container">
            <div class="questionlist_wrap">
                <div class="addremove_container">
                    <div class="q_additem" onclick="newquestion(this)">+</div>
                    <div class="q_removeitem" onclick="removequestion(this)">-</div>
                </div>
                <div class="question_listitem tab-active" data-questionindex="1" onclick="showquestion(this)">Soru 1</div>
            </div>
        </div>
        <div class="ns-right_container">
            <div class="question_container tab-activeq tab-fade" data-question="1">
                <input type="hidden" name="questionid" value="1">
                <span class="question_index">Soru 1:</span>
                <div class="question_content">
                    <input name="1-question" type="text" placeholder="Soru">
                    <button class="addanswer" type="button" onclick="newanswer(this)">Cevap ekle</button>
                    <div class="answer_item">
                        <span class="answer_index">Cevap: <button class="deleteanswer" type="button" onclick="deleteanswer(this)">Sil</button></span>
                        <input name="1-answer" type="text" placeholder="Cevap">
                    </div>
                    <div class="answer_item">
                        <span class="answer_index">Cevap: <button class="deleteanswer" type="button" onclick="deleteanswer(this)">Sil</button></span>
                        <input name="1-answer" type="text" placeholder="Cevap">
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock content %}

surveyville/templates/survey.html
{% extends "template_1.html" %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static '/css/surveydetail.css' %}">
{% endblock head %}

{% block content %}
    <form class="survey_wraper" action="{% url 'submitsurvey' %}" method="post">
        <span class="s_title">{{survey.s_title}}</span>
        <span class="s_description">{{survey.s_text}}</span>
        <div class="s_questions_cont">
            {% for question in questions %}
            <div class="s_question">
                <span class="s_questiontitle">Soru: {{question.q_text}}</span>
                <div class="s_answers">
                    <input type="hidden" name="question" value="{{question.id}}">
                    {% for answer in question.answer_set.all %}
                    <label class="s_answer"><input type="radio" name="{{question.id}}-answer" value="{{answer.id}}" class="s_radio">{{answer.a_text}}</label>
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="s_buttons">
            <button class="s_cancelbtn" type="button" onclick="location.href='{% url 'index' %}'">Çık</button>
            <input class="s_finishbtn" type="submit" value="Bitir">
        </div>
    </form>
{% endblock content %}

surveyville/templates/surveyresult.html
{% extends "template_1.html" %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static '/css/surveydetail.css' %}">
{% endblock head %}

{% block content %}

<div class="survey_wraper">
    <span class="s_title">{{survey.s_title}}</span>
    <span class="s_description">{{survey.s_text}}</span>
    <div class="s_questions_cont">
        {% for question in questions %}
        <div class="s_question">
            <span class="s_questiontitle">Soru: {{question.q_text}}</span>
            <div class="s_answers">
                <input type="hidden" name="question" value="{{question.id}}">
                {% for answer in question.answer_set.all %}
                <label class="s_answer"><span class="s_answervotes">{{answer.vote_set.count}}</span> | {{answer.a_text}}</label>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

surveyville/templates/template_1.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="{% static '/css/template.css' %}">
    <link rel="stylesheet" href="{% static '/css/responsive.css' %}">
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <link rel="stylesheet" href="{% static '/css/modal.css' %}">
    <script src="{% static '/js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static '/js/script.js' %}"></script>
    
    {% block head %}
            
    {% endblock %}
    <title>Surveyville</title>
</head>
<body>
    <div class="modal-container" id="login-modal">
        <form action="signin/" method="POST" class="modal">
            <button type="button" class="close-modal">×</button>
            <div class="modal-header">
                <h2>Giriş Yap</h2>
            </div>
            <div class="modal-form">
                <input type="text" name="username" placeholder="Kullanıcı Adı">
                <input type="text" name="password" placeholder="Şifre">
            </div>
            <div class="modal-btn-wrap">
                <input type="submit" value="Giriş" class="login-btn">
            </div>
        </form>
    </div>
    <div class="modal-container" id="signup-modal">
        <form action="createuser/" method="POST" class="modal">
            <button type="button" class="close-modal">×</button>
            <div class="modal-header">
                <h2>Kayıt Ol</h2>
            </div>
            <div class="modal-form">
                <input type="text" name="email" placeholder="E-Mail">
                <input type="text" name="username" placeholder="Kullanıcı Adı">
                <input type="text" name="password" placeholder="Şifre">
            </div>
            <div class="modal-btn-wrap">
                <input type="submit" value="Kayıt Ol" class="signup-btn">
            </div>
        </form>
    </div>

    <div class="content_block">
        <!-- top_title -->
        <div class="top_title">
            <div class="wraper">
                <h2 class="header_logo"><a href="{% url 'index' %}">SURVEYVILLE</a> <span>Anket konulu projem - 222003545</span></h2>
                <div class="account-wrap">
                    {% if user.is_authenticated %}
                    <button class="anketolustur-btn" onclick="location.href='{% url 'newsurvey' %}'">Anket Oluştur</button>
                    <!-- <input type="button" value="Anket Oluştur" class="anketolustur-btn"> -->
                    <button class="profile" onclick="pfDropdown()">PROFİL<span class="pbtnarrowdown"><</span></button>
                    <ul class="pf_dropdown">
                        <li><a href="#">{{user.username}}</a></li>
                        <li><a href="#">Anketlerim</a></li>
                        <li><a href="#">boş text</a></li>
                        <li><a href="{% url 'logout' %}">Çıkış yap</a></li>
                    </ul>
                    {% else %}
                    <input type="button" value="Giriş Yap" class="open-login" data-modal="login-modal" onclick="showModal(this)">
                    <input type="button" value="Kayıt Ol" class="open-signin" data-modal="signup-modal" onclick="showModal(this)">
                    {% endif %}
                </div>
            </div>
        </div>
        <!-- /top_title -->
        <div class="wraper content-wraper">
            {% block content %}
            
            {% endblock %}
            <!--
            <div class="long_text_layout long_text_col_2 gallery">
                <ul class="survey_ul">
                    <li>
                        <div class="desc">
                            <h5>Sosyal medya uygulaması analizi</h5>
                            <span class="expire_date">2 gün kaldı</span>
                            <p>Bu ankete katılarak sosyal medya uygulamalarını oylayın.</p>
                            <p><b>423 Katılımcı</b></p>
                            <input type="button" value="Ankete Katıl" class="anket-btn">
                        </div>
                    </li>
                </ul>
            </div>
            -->
            <!-- /Short Text Layout 3 Column -->
        </div>
    </div>


</body>
</html>